### ISSUE TITLE
infinispan/cli fails

### ISSUE THREAD

**Issue by sschueller** [infinispan/infinispan-images#118]
Starting the latest cli docker image fails with following error:

```
Unable to find image 'infinispan/cli:12.0' locally
12.0: Pulling from infinispan/cli
Digest: sha256:906da07331a7e1c55eb363f60791592640b1253e84ef6d375c1500d512ad8ee6
Status: Downloaded newer image for infinispan/cli:12.0
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Could not instantiate class: class org.infinispan.cli.impl.ExitCodeResultHandler, no access to constructors.
	at org.infinispan.cli.commands.CLI.main(CLI.java:330)
	at org.infinispan.cli.commands.CLI.main(CLI.java:339)
	at org.infinispan.cli.quarkus.CliQuarkus.main(CliQuarkus.java:14)
Caused by: java.lang.RuntimeException: Could not instantiate class: class org.infinispan.cli.impl.ExitCodeResultHandler, no access to constructors.
	at org.aesh.util.ReflectionUtil.newInstance(ReflectionUtil.java:48)
	at org.aesh.command.impl.internal.ProcessedCommandBuilder.initResultHandler(ProcessedCommandBuilder.java:129)
	at org.aesh.command.impl.internal.ProcessedCommandBuilder.resultHandler(ProcessedCommandBuilder.java:123)
	at org.aesh.command.impl.container.AeshCommandContainerBuilder.doGenerateCommandLineParser(AeshCommandContainerBuilder.java:87)
	at org.aesh.command.impl.container.AeshCommandContainerBuilder.doGenerateCommandLineParser(AeshCommandContainerBuilder.java:138)
	at org.aesh.command.impl.container.AeshCommandContainerBuilder.create(AeshCommandContainerBuilder.java:73)
	at org.aesh.command.impl.registry.MutableCommandRegistryImpl.addCommand(MutableCommandRegistryImpl.java:133)
	at org.aesh.command.impl.registry.AeshCommandRegistryBuilder.command(AeshCommandRegistryBuilder.java:57)
	at org.infinispan.cli.commands.CLI.initialCommandRuntimeBuilder(CLI.java:304)
	at org.infinispan.cli.commands.CLI.main(CLI.java:326)
	... 2 more
```

- infinispan/cli:12.0.0.Final - works
- infinispan/cli:12.0.0.Final-1 - works
- infinispan/cli:12.0.0.Final-2 - works
- infinispan/cli:12.0.1.Final - fails
- infinispan/cli:12.0.1.Final-1 - fails
- infinispan/cli:12.0 - fails
- infinispan/cli:latest - fails

**Comment by ryanemerson** [comment]
@sschueller Thanks for reporting the issue. I have fixed the underlying issue and re-released the cli image as `12.0.1.Final-2`. The `12.0`, `latest` and `12.0.1.Final` tags have all been updated.
